version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=829338826705.dkr.ecr.eu-north-1.amazonaws.com/webservice
      - COMMIT_HASH="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_TAG="${REPOSITORY_URI}:${TAG}"

  install:
    runtime-versions:
      java: corretto11

  build:
    commands:
      - echo Build started on `date`

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
    - target/messageUtil-1.0.jar
  base-directory: './build/libs'
reports:
      test-report-group: #Junit reports
        files:
          - 'TEST-boris.maths.MathsApplicationTests.xml'
        #discard-paths: false #do not remove file paths from test result files
        base-directory: './build/test-results/test'
